### PR TITLE
Drop support for EOL Python 2.6, 2.7, 3.3 and 3.4

### PR DESCRIPTION
**Pull request by hugovk**
Python 2.6, 3.3 and 3.4 are EOL and no longer receiving security updates (or any updates) from the core Python team.

Version | Release date | Supported until
--- | ---------- | ----------
2.5 | 2006-09-19 | 2011-05-26
2.6 | 2008-10-01 | 2013-10-29
2.7 | 2010-07-03 | 2020-01-01
3.0 | 2008-12-03 | 2009-06-27
3.1 | 2009-06-27 | 2012-04-09
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

Python 2.6 and 3.3 have not been tested by the CI for some time, meaning it's not certain if it still works on those versions. Dropping them allows code to be modernised and reduce maintenance burden.

They're also little used. Here's the pip installs for toml from PyPI for June 2019:

| category | percent | downloads |
|----------|--------:|----------:|
|      3.6 |  38.78% |   915,480 |
|      3.7 |  27.11% |   640,020 |
|      2.7 |  23.35% |   551,139 |
|      3.5 |   7.76% |   183,195 |
|      3.4 |   1.39% |    32,754 |
| null     |   1.27% |    29,881 |
|      3.8 |   0.23% |     5,466 |
|      2.6 |   0.07% |     1,680 |
|      3.3 |   0.03% |       716 |
|      3.2 |   0.00% |        73 |
|      3.9 |   0.00% |         7 |
|      3.1 |   0.00% |         1 |
| Total    |         | 2,360,412 |

Source: `pypistats python_minor toml --last-month # pip install pypistats`

`python_requires` ensures people can still install an older version of toml.

### CODE REVIEW

**Comment by macisamuele** [comment]
Is there any update on this?

**Comment by uiri** [comment]
Happy New Year!

How about dropping Python 2.7 (or Python 2 in general) as well?

I think I will make one more release with support for these "deprecated" versions before dropping them.

**Comment by hugovk** [comment]
Good idea, updated! Sounds sensible to make one last release too.

Happy new year!

**Comment by robertwenner** [comment]
How much code is actually needed to support Python 2.7? What does it gain to drop support? I'm asking cause I'm stuck with an old code base for a few more months.

**Comment by hugovk** [comment]
Merge conflict resolved!

Passing CI build:

* https://travis-ci.com/github/hugovk/toml/builds/199472669

We could also drop Python 3.5 which is EOL now, and use f-strings! Thoughts?

**Comment by hugovk** [comment]
Closing this 2.5-year-old PR as this projects appears unmaintained (see https://github.com/uiri/toml/issues/361), but happy to re-open if this changes 👍

**Pull request closed without merging**
