### PR TITLE
Add support for inline objects

### LINKED ISSUE #40: Inline table support
When I try to parse a file that contains an inline table (as defined by [toml 0.4](https://github.com/toml-lang/toml#user-content-inline-table), the parser crashes. For intance, with:
```
origins_to_ranks = {nomderue = 20, communes = 10}
```

I get.
```
  File "/home/jenselme/Stage3A/geo-api3/chsdi/tests/functional/test_sphinx.py", line 26, in test_sphinx_api_query
    config = toml.load(config_file)
  File "/home/jenselme/Stage3A/geo-api3/.venv/lib/python3.4/site-packages/toml.py", line 43, in load
    return loads(f.read(), _dict)
  File "/home/jenselme/Stage3A/geo-api3/.venv/lib/python3.4/site-packages/toml.py", line 331, in loads
    value, vtype = load_value(pair[1])
  File "/home/jenselme/Stage3A/geo-api3/.venv/lib/python3.4/site-packages/toml.py", line 453, in load_value
    parsed_date = load_date(v)
  File "/home/jenselme/Stage3A/geo-api3/.venv/lib/python3.4/site-packages/toml.py", line 350, in load_date
    tz = TomlTz(val[19:24])
  File "/home/jenselme/Stage3A/geo-api3/.venv/lib/python3.4/site-packages/toml.py", line 9, in __new__
    self._hours = int(toml_offset[:3])
ValueError: invalid literal for int() with base 10: 'omm'
```

Can you add support for this syntax please?

### PR DESCRIPTION
**Pull request by Jenselme**
Close #40

### CODE REVIEW

**Comment by AluisioASG** [comment]
Doesn't seem to support inline tables inside arrays:
```python
>>> import toml
>>> s = """
... points = [ { x = 1, y = 2, z = 3 },
...            { x = 7, y = 8, z = 9 },
...            { x = 2, y = 4, z = 8 } ]
... """
>>> toml.loads(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "toml.py", line 296, in loads
    status = load_line(line, currentlevel, multikey, multibackslash)
  File "toml.py", line 351, in load_line
    value, vtype = load_value(pair[1])
  File "toml.py", line 470, in load_value
    return (load_array(v), "array")
  File "toml.py", line 532, in load_array
    nval, ntype = load_value(a[i])
  File "toml.py", line 490, in load_value
    v = int(v)
ValueError: invalid literal for int() with base 10: '{ x = 1'
```

**Comment by Jenselme** [comment]
True, I will have to do more work on it then.

**Comment by Jenselme** [comment]
I think its good. With

```ini
[test]
{coucou = "Salut toi"}

[testarray]
a = [ {zut = "oops"} ]
points = [ { x = 1, y = 2, z = 3 },
	{ x = 7, y = 8, z = 9 },
	{ x = 2, y = 4, z = 8 } ]
	
my_points = [ { x = 1, y = 2, z = 3 }, { x = 7, y = 8, z = 9 }, { x = 2, y = 4, z = 8 } ]
```

I get:

```json
{
    "testarray": {
        "a": [
            {
                "zut": "oops"
            }
        ],
        "points": [
            {
                "x": 1,
                "z": 3,
                "y": 2
            },
            {
                "x": 7,
                "z": 9,
                "y": 8
            },
            {
                "x": 2,
                "z": 8,
                "y": 4
            }
        ],
        "my_points": [
            {
                "x": 1,
                "z": 3,
                "y": 2
            },
            {
                "x": 7,
                "z": 9,
                "y": 8
            },
            {
                "x": 2,
                "z": 8,
                "y": 4
            }
        ]
    },
    "test": {
        "coucou": "Salut toi"
    }
}
```

**Comment by uiri** [comment]
This breaks 3 tests in the toml test suite: key-equals-nospace, multiline-string and raw-multiline-string.

**Comment by Jenselme** [comment]
Just pushed some corrections. This time it looks good:

```
~/projects/toml-test  master ✗                                                                                                                                                                           347d ◒  ⍉
▶ ./toml-test ../toml/toml_test3.py
Test: datetime-malformed-no-z (invalid)

Expected an error, but no error was reported.

77 passed, 1 failed

~/projects/toml-test  master ✗                                                                                                                                                                           347d ◒  ⍉
▶ ./toml-test ../toml/toml_test.py 
Test: datetime-malformed-no-z (invalid)

Expected an error, but no error was reported.

77 passed, 1 failed
```

**Comment by uiri** [comment]
Yep, it passes all the same tests that master does on my machine as well on both python 2 and python 3. I'm going to review the code to make sure I understand it before merging it into master.

If you want to add yourself to the copyright notice in the LICENSE file feel free to make that change and add it to this pull request.

**Comment by uiri** [comment]
During my further manual testing, I discovered that your patch doesn't properly handle commas inside of strings.

A toml file like the following triggers the bug:

```ini
test = {a = "This, is", b = "a, test" }
```

**Comment by Jenselme** [comment]
@uiri Normally commas are correctly supported now.

**Comment by Jayflux** [comment]
pokes @uiri 
Anything stopping this from being merged in?

**Comment by Jayflux** [comment]
@Jenselme  your branch seems to fail when i try to parse this:
https://gist.github.com/Jayflux/6f1b46d4ed7e07322a5e

Any ideas?

**Comment by Jayflux** [comment]
https://github.com/Jenselme/toml/blob/inline-objects/toml.py#L315 will always fail if you're currently on the last candidate group
Maybe it needs rethinking?

**Comment by Jenselme** [comment]
@Jayflux thanks for the patch. I just tested it and it works. I didn't know you could add arrays inside inline objects, so I didn't test it.

I just cherry-picked the commit and push it to this branch. @uiri What do you think?

**Comment by uiri** [comment]
A few comments on the PR as it currently stands:

- The test toml files should be sent as a patch to the toml-test suite maintained by @BurntSushi rather than be included here
- load_inline_object doesn't have a return statement but its return value is used in a conditional in loads. Is this intentional? Why?
- I think the checks on the status to continue are unnecessary since those `continue` statements are the last statements in those loops
- I feel like the algorithm in load_array to match different parenthesis groups could be more efficient/concise. Perhaps using regular expressions?

I think everything else is OK.

**Comment by Jenselme** [comment]
> - The test toml files should be sent as a patch to the toml-test suite maintained by @BurntSushi rather than be included here

I never meant to include them. I guess I did a wrong `git add`.

> - load_inline_object doesn't have a return statement but its return value is used in a conditional in loads. Is this intentional? Why?

I guess it was needed once but not any more. Removed.

> - I think the checks on the status to continue are unnecessary since those `continue` statements are the last statements in those loops

Indeed, status removed

> - I feel like the algorithm in load_array to match different parenthesis groups could be more efficient/concise. Perhaps using regular expressions?

I gave it a try here: https://github.com/Jenselme/toml/tree/re-inline-objects-in-array and it got me thinking: what if we have this (a closing curly bracket in a string in an inline object in an array):
```
array_str = [ {a = "I * } testing", b = "Yolo"} ]
```

I just updated my code to handle this, but I don't see how to support it with a regexp. Do you have an idea?

**Comment by Jayflux** [comment]
pings @uiri about the above

**Comment by jdm** [comment]
It would be really lovely to make some progress here!

**Comment by uiri** [comment]
Hey all,

I want to apologize for letting this PR sit for so long. I know I did go through it rather thoroughly in January and listed out my concerns then. I think that there might still be some bugs but the obvious cases seem to have been taken care of. I think progress needs to be made in the test suite so that implementations of the TOML standard can stay up to date as that standard evolves. To that end, I'm switching to the fork of @BurntSushi's test suite maintained by @avakar since it seems to have the most recent set of tests.

Side note @jdm: I really enjoyed your talk at CUSEC this year.

**Pull request merged**
