### PR TITLE
Feature: Let load() handle non-existing files in list.

### PR DESCRIPTION
**Pull request by x10an14**
As long as there's at least _one_ existing file in the list given.
To permit things like the examples listed here: https://github.com/uiri/toml/issues/9#issuecomment-17939193

Hopefully the result becomes either what's in `config.ini` or `config_dev.ini` if either's opposite is non-existent on the filesystem.

### CODE REVIEW

**Comment by uiri** [comment]
Hi x10an14,

Thank you for your pull request! I am sorry it took me a little while to take a proper look at it.

It looks like you made a typo and wrote `exist` instead of `exists`. I would prefer `path.exists` to `op.exists` but it is a matter of personal preference.

In the case of a list with some existent and some nonexistent filenames, the `load` still raises an error on the nonexistent files. I think it should just ignore the nonexistent filenames and error out if there are no existent filenames in the list. You already wrote the code, it is just commented out :)

I don't think a lack of valid filenames should be a TypeError since all the items in the list are the right type. I am leaning towards a ValueError or an IOError instead.

I think linesep might be useful elsewhere in the code. In which case, importing it in a larger scope would make sense.

Thanks again!

**Comment by x10an14** [comment]
Hi @uiri! =)

Thanks for the feedback! And don't worry about the promptness =).
Let me respond to your feedback point-by-point:

- > It looks like you made a typo and wrote `exist` instead of `exists`.

Sorry! My bad! I'll check why my linter didn't catch that. In any case, I probably ought to re-run the tests, which I thought I had done...

- > I would prefer `path.exists` to `op.exists` but it is a matter of personal preference.

Yeah, like you say, personal preference =). Feel free to revert/change that if you so choose!
My reasoning for using `op` instead of `path`:

1. Any `from x import y` is (for me) a shorthand to save on horizontal space, so you don't need to write `x.y` everywhere (which can become long in our case: `os.path.exists`). This I find especially important when trying to respect a maximum horizontal line length of 79/80/119/120.
Imagine the case where you want to get the real and absolute filepath of something:
`os.path.abspath(os.path.realpath(os.path.join(some_path, some_file))))` vs `op.abspath(op.realpath(op.join(some_path, some_file)))`
2. I 'chose' the `os` shorthand in that regard, with the little logic that it's from the `os` module, and the `path` submodule. But again, I won't feel slighted at all if you prefer to change it for your own readability!

- > In the case of a list with some existent and some nonexistent filenames, the `load` still raises an error on the nonexistent files.

'Twas intentional in the hope to raise some discussion about the behaviour you'd prefer! =D
  * >  I think it should just ignore the nonexistent filenames and error out if there are no existent filenames in the list. You already wrote the code, it is just commented out :)

Done! =)

- > I don't think a lack of valid filenames should be a TypeError since all the items in the list are the right type. I am leaning towards a ValueError or an IOError instead.

I was wondering the same, but I wanted your input (again, trying to provoke discussion by leaving it be^^).
Personally I find it more "Pythonic" with `ValueError`, but more 'correctly descriptive' with `IOError`.
How'd you feel about `FileNotFoundError`?

- > I think linesep might be useful elsewhere in the code. In which case, importing it in a larger scope would make sense.

I'll fix that in a separate commit! I'll see what I can find =) Maybe just aswell a different pull-request?

**Comment by x10an14** [comment]
I found out why I didn't run your tests. I didn't figure out how to!

I found your file [TESTING](https://github.com/uiri/toml/blob/3869c1dd250dfcce98fa8acdaac06c25a5b3e159/TESTING), and I installed Go, managed to execute its 'default tests', but that's as far as I got =/.

See [my gist](https://gist.github.com/x10an14/5fc87eb45e1ec6564ecb3a083bf095e0) for my attempt!

**Comment by x10an14** [comment]
@uiri I also see now in your [.travis.yml](https://github.com/uiri/toml/blob/dab00e9880506bc48ec3575f66f5b6ea6f82e998/.travis.yml) that you actually don't use these `toml_test.py`/`toml_test3.py`. 

Would you mind if I make another PR for updating your testing instructions? =)

**Comment by uiri** [comment]
I am sorry that the Testing documentation is lagging behind the actual code and operations. I have more improvements I want to make to the testing. The most significant one is adding tests for all the resolved issues to catch regressions.

> - > It looks like you made a typo and wrote `exist` instead of `exists`.
> 
> Sorry! My bad! I'll check why my linter didn't catch that. In any case, I probably ought to re-run the tests, which I thought I had done...

The tests don't execute that code path. They test language agnostic encoding and decoding thoroughly. The coverage for the actual python API is scarce.
 
> - > In the case of a list with some existent and some nonexistent filenames, the `load` still raises an error on the nonexistent files.
> 
> 'Twas intentional in the hope to raise some discussion about the behaviour you'd prefer! =D

I think perhaps there should still be a warning that some of the files were not found. I can look into that if you are unfamiliar with Python's warning facilities.

> I was wondering the same, but I wanted your input (again, trying to provoke discussion by leaving it be^^).
> Personally I find it more "Pythonic" with `ValueError`, but more 'correctly descriptive' with `IOError`.
> How'd you feel about `FileNotFoundError`?

FileNotFoundError does not exist in Python 2. I think IOError for Python 2 and FileNotFoundError for Python 3 makes the most sense. FileNotFoundError only exists in version Python 3.3 or later but that is fine since we are not targeting earlier Python 3 versions.

Thanks again for your PR and muddling through the poorly documented testing procedures.

**Comment by x10an14** [comment]
> I am sorry that the Testing documentation is lagging behind the actual code and operations. I have more improvements I want to make to the testing. 

No worries =).
Didn't mean to call you out on anything lacking, would be happy to prepare my PRs better if you don't mind me communicating with you over email.

> The tests don't execute that code path. They test language agnostic encoding and decoding thoroughly. The coverage for the actual python API is scarce.

Ahh okay. 
As you might've gathered, I'm not that good/into Go. 
My interest lies primarily in Python as opposed to Go. 
I don't mind leaving the actual TOML decoding tests to your Go suite or something else, but I could perhaps be interested in improving the Python coverage (at least for Python3).

> I think perhaps there should still be a warning that some of the files were not found. I can look into that if you are unfamiliar with Python's warning facilities.

I must admit I had never heard of the `import warning` module before you mentioned it here. 
I'm not quite sure how you'd like it's implementation, since I'm getting the feeling that our programming styles diverge some.
So if you wouldn't mind giving some examples/commit(s) to this branch, then I could take it from there if you'd like!
(I must admit I was wondering how to send execution updates to the users through stderr, and this seems like the 'correct' way to do it, although I must admit I like [this S/O answer](https://stackoverflow.com/a/14981125)).

> FileNotFoundError does not exist in Python 2. I think IOError for Python 2 and FileNotFoundError for Python 3 makes the most sense. FileNotFoundError only exists in version Python 3.3 or later but that is fine since we are not targeting earlier Python 3 versions.

Alright!
Commit incoming!

> Thanks again for your PR and muddling through the poorly documented testing procedures.

No worries & my pleasure =). 
Please don't hesitate to call me out on anything if there's something you dislike/would like to discuss about my PRs.

**Comment by uiri** [comment]
This looks good to me. Merge'd.

> [...]  would be happy to prepare my PRs better if you don't mind me communicating with you over email.

Feel free. My email is in the commit logs for a reason.

I opened up #104 to track the warning issue. I haven't used `import warning` before either so I'm afraid I don't have any ready examples to point to.

**Pull request merged**
